import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const products=['All products','Business Checking','Consumer Checking','Business Savings','Consumer Savings'];
const money=n=>'$'+n+'M';

function Bars({values,labels,comparison=[]}){return <div className="bars">{values.map((v,i)=><div className="barWrap" key={labels[i]}><div className="barPair"><i style={{height:v}}></i>{comparison[i]&&<i className="compare" style={{height:comparison[i]}}></i>}</div><small>{labels[i]}</small></div>)}</div>}
function Row({label,value,width,tone=''}){return <div className="row"><span>{label}</span><div><i className={tone} style={{width}}></i></div><b>{value}</b></div>}
function Score({label,value,note,status='good'}){return <div className="score"><span>{label}</span><b>{value}</b><small className={status}>{note}</small></div>}

function viewFor(product,m){
  const shared={
    'Business Checking':{title:'Business checking performance',subtitle:'Operating balances, payment activity, acquisition, and treasury engagement.',cards:[['Operating deposits',money(m.depositsMillions),'↑ 6.8%'],['Active businesses','12,480','↑ 4.1%'],['Treasury attach','38.6%','↑ 2.7 pts'],['Payment fraud',m.fraudRate+'%','↓ 0.04 pts']],trendTitle:'Payment activity',trendSub:'ACH, wire, and debit transaction volume by week',trend:[60,74,68,88,81,104],compare:[52,61,65,72,79,86],labels:['W1','W2','W3','W4','W5','W6'],sideTitle:'Business engagement',sideSub:'Products that deepen the primary relationship',sideRows:[['Treasury services','38.6%','39%'],['ACH active','72.4%','72%'],['Card active','61.8%','62%'],['Payroll linked','43.2%','43%']],bottomTitle:'Business acquisition funnel',bottomRows:[['Applied',m.applications.toLocaleString(),'100%'],['Approved',Math.round(m.applications*m.approvalRate/100).toLocaleString(),'74%'],['Funded','3,121','68%'],['Active at 90d','2,814','61%']]},
    'Consumer Checking':{title:'Consumer checking performance',subtitle:'Primary-bank behavior, card engagement, direct deposit, and attrition.',cards:[['Checking deposits',money(m.depositsMillions),'↑ 3.9%'],['Primary-bank rate','64.1%','↑ 1.8 pts'],['Direct deposit','71.6%','↑ 2.4 pts'],['Monthly churn',m.monthlyChurnRate+'%','↓ 0.2 pts']],trendTitle:'Debit spend & transactions',trendSub:'Weekly card activity versus prior period',trend:[64,71,78,73,94,102],compare:[58,66,69,74,81,88],labels:['W1','W2','W3','W4','W5','W6'],sideTitle:'Customer engagement',sideSub:'Behaviors associated with primary relationships',sideRows:[['Direct deposit','71.6%','72%'],['Debit active','83.2%','83%'],['Digital active','88.5%','89%'],['Overdraft-free','94.7%','95%']],bottomTitle:'Consumer acquisition funnel',bottomRows:[['Applied',m.applications.toLocaleString(),'100%'],['Approved',Math.round(m.applications*m.approvalRate/100).toLocaleString(),'70%'],['Funded','4,522','67%'],['Active at 90d','4,114','61%']]},
    'Business Savings':{title:'Business savings & liquidity',subtitle:'Liquidity reserves, yield sensitivity, retention, and relationship depth.',cards:[['Savings deposits',money(m.depositsMillions),'↑ 7.6%'],['Net new money','$6.4M','↑ 12.2%'],['Avg rate paid','3.72%','↑ 8 bps'],['12-mo retention',m.retentionRate+'%','↑ 1.3 pts']],trendTitle:'Balance & net flow trend',trendSub:'Weekly ending balance versus growth plan',trend:[63,69,77,86,91,106],compare:[58,64,70,76,83,90],labels:['W1','W2','W3','W4','W5','W6'],sideTitle:'Liquidity profile',sideSub:'Business savings behavior and pricing exposure',sideRows:[['High balance','44.8%','45%'],['Rate sensitive','31.2%','31%'],['Operating reserve','68.5%','69%'],['Relationship linked','79.1%','79%']],bottomTitle:'Savings relationship funnel',bottomRows:[['Eligible businesses','8,420','100%'],['Offer viewed','5,980','71%'],['Account opened','2,391','28%'],['90d retained','2,236','27%']]},
    'Consumer Savings':{title:'Consumer savings growth',subtitle:'Net flows, recurring savings, rate response, goals, and retention.',cards:[['Savings deposits',money(m.depositsMillions),'↑ 5.1%'],['Net inflows','$4.8M','↑ 9.7%'],['Recurring savers','42.6%','↑ 3.1 pts'],['Monthly churn',m.monthlyChurnRate+'%','↓ 0.3 pts']],trendTitle:'Savings balance growth',trendSub:'Weekly balances versus growth plan',trend:[58,66,71,79,91,99],compare:[54,60,66,72,78,84],labels:['W1','W2','W3','W4','W5','W6'],sideTitle:'Savings behavior',sideSub:'Signals of durable household balances',sideRows:[['Recurring save','42.6%','43%'],['Goal funded','36.8%','37%'],['Rate sensitive','28.4%','28%'],['90d retained','91.2%','91%']],bottomTitle:'Savings acquisition funnel',bottomRows:[['Offer reached','18,400','100%'],['Started','8,760','48%'],['Funded','5,079','28%'],['90d retained','4,632','25%']]}
  };
  if(product!=='All products')return shared[product];
  return {title:'Executive portfolio overview',subtitle:'Enterprise view across deposits, growth, profitability, risk, customers, and platform health.',cards:[['Total deposits',money(m.depositsMillions),'↑ 5.2%'],['Net new money','$24.8M','↑ 8.7%'],['Net interest margin','3.12%','↑ 6 bps'],['Fraud loss rate',m.fraudRate+'%','↓ 0.06 pts']],trendTitle:'Portfolio deposits vs plan',trendSub:'Monthly ending balances across all products',trend:[58,63,71,78,86,98],compare:[55,60,66,72,79,86],labels:['Mar','Apr','May','Jun','Jul','Aug'],sideTitle:'Product deposit mix',sideSub:'Share of total relationship balances',sideRows:[['Business checking','38%','38%'],['Consumer checking','26%','26%'],['Business savings','18%','18%'],['Consumer savings','18%','18%']],bottomTitle:'Enterprise growth funnel',bottomRows:[['Applications',m.applications.toLocaleString(),'100%'],['Approved','13,256','72%'],['Funded','11,632','63%'],['Active at 90d','10,984','59%']]};
}

function App(){
  const [product,setProduct]=useState(products[0]); const [m,setM]=useState(null);
  useEffect(()=>{setM(null);fetch('http://localhost:8080/api/metrics?product='+encodeURIComponent(product)).then(r=>r.json()).then(setM)},[product]);
  if(!m)return <main className="loading">Loading portfolio…</main>;
  const v=viewFor(product,m);
  return <><header><b>Northstar</b><span>Executive banking intelligence · Synthetic portfolio</span></header><main>
    <nav>{products.map(p=><button className={p===product?'active':''} onClick={()=>setProduct(p)} key={p}>{p}</button>)}</nav>
    <div className="heading"><div><h1>{v.title}</h1><p>{v.subtitle}</p></div><span className="fresh">Updated 2 min ago</span></div>
    <section className="cards">{v.cards.map(([l,val,d])=><article key={l}><small>{l}</small><strong>{val}</strong><em>{d} vs prior period</em></article>)}</section>
    {product==='All products'&&<section className="scoreStrip"><Score label="Return on assets" value="1.41%" note="Above plan"/><Score label="Cost-to-income" value="48.6%" note="Improving"/><Score label="Customer NPS" value="+47" note="Top quartile"/><Score label="At-risk deposits" value="$9.6M" note="Needs attention" status="watch"/></section>}
    <section className="grid"><article className="panel wide"><h2>{v.trendTitle}</h2><p>{v.trendSub}</p><div className="legendLine"><span>■ Actual</span><span>■ Plan / prior</span></div><Bars values={v.trend} comparison={v.compare} labels={v.labels}/></article><article className="panel"><h2>{v.sideTitle}</h2><p>{v.sideSub}</p>{v.sideRows.map(([l,val,w],i)=><Row key={l} label={l} value={val} width={w} tone={i===3?'light':i===2?'gray':''}/>)}</article></section>
    <section className="grid"><article className="panel"><h2>{v.bottomTitle}</h2><p>Conversion and activation through the selected journey</p>{v.bottomRows.map(([l,val,w],i)=><Row key={l} label={l} value={val} width={w} tone={i>1?'light':''}/>)}</article><article className="panel"><h2>Retention & risk</h2><p>Early-warning customer and balance indicators</p><Row label="Monthly churn" value={m.monthlyChurnRate+'%'} width="19%" tone="red"/><Row label="At-risk customers" value={m.atRiskCustomers.toLocaleString()} width="31%"/><Row label="Balances at risk" value={money(m.depositsAtRiskMillions)} width="28%"/><Row label="Win-back rate" value={m.winBackRate+'%'} width="42%" tone="light"/></article></section>
    {product==='All products'&&<><h3>Leadership operating scorecard</h3><section className="scoreStrip tech"><Score label="Digital acquisition" value="62.8%" note="↑ 4.2 pts"/><Score label="Marketing CAC" value="$84" note="↓ 6.7%"/><Score label="Deposit beta" value="44.1%" note="Within guardrail"/><Score label="Promo conversion" value="14.8%" note="↑ 1.9 pts"/></section><h3>Technology & data health</h3><section className="scoreStrip tech"><Score label="API availability" value="99.98%" note="Healthy"/><Score label="P95 API latency" value="184 ms" note="Within SLO"/><Score label="Data freshness" value="2 min" note="Current"/><Score label="Pipeline success" value="99.6%" note="1 retry" status="watch"/></section></>}
  </main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
